/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class ApprovedTermExtension {

    @JsonProperty("capitalize")
    private boolean capitalize;

    @JsonProperty("fixCase")
    private boolean fixCase;

    @JsonProperty("fixCommonMistakes")
    private boolean fixCommonMistakes;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<? extends Long> id;

    @JsonProperty("termId")
    private long termId;

    @JsonCreator
    public ApprovedTermExtension(
            @JsonProperty("capitalize") boolean capitalize,
            @JsonProperty("fixCase") boolean fixCase,
            @JsonProperty("fixCommonMistakes") boolean fixCommonMistakes,
            @JsonProperty("id") Optional<? extends Long> id,
            @JsonProperty("termId") long termId) {
        Utils.checkNotNull(capitalize, "capitalize");
        Utils.checkNotNull(fixCase, "fixCase");
        Utils.checkNotNull(fixCommonMistakes, "fixCommonMistakes");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(termId, "termId");
        this.capitalize = capitalize;
        this.fixCase = fixCase;
        this.fixCommonMistakes = fixCommonMistakes;
        this.id = id;
        this.termId = termId;
    }
    
    public ApprovedTermExtension(
            boolean capitalize,
            boolean fixCase,
            boolean fixCommonMistakes,
            long termId) {
        this(capitalize, fixCase, fixCommonMistakes, Optional.empty(), termId);
    }

    @JsonIgnore
    public boolean capitalize() {
        return capitalize;
    }

    @JsonIgnore
    public boolean fixCase() {
        return fixCase;
    }

    @JsonIgnore
    public boolean fixCommonMistakes() {
        return fixCommonMistakes;
    }

    @JsonIgnore
    public Optional<? extends Long> id() {
        return id;
    }

    @JsonIgnore
    public long termId() {
        return termId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ApprovedTermExtension withCapitalize(boolean capitalize) {
        Utils.checkNotNull(capitalize, "capitalize");
        this.capitalize = capitalize;
        return this;
    }

    public ApprovedTermExtension withFixCase(boolean fixCase) {
        Utils.checkNotNull(fixCase, "fixCase");
        this.fixCase = fixCase;
        return this;
    }

    public ApprovedTermExtension withFixCommonMistakes(boolean fixCommonMistakes) {
        Utils.checkNotNull(fixCommonMistakes, "fixCommonMistakes");
        this.fixCommonMistakes = fixCommonMistakes;
        return this;
    }

    public ApprovedTermExtension withId(long id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }

    public ApprovedTermExtension withId(Optional<? extends Long> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public ApprovedTermExtension withTermId(long termId) {
        Utils.checkNotNull(termId, "termId");
        this.termId = termId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApprovedTermExtension other = (ApprovedTermExtension) o;
        return 
            java.util.Objects.deepEquals(this.capitalize, other.capitalize) &&
            java.util.Objects.deepEquals(this.fixCase, other.fixCase) &&
            java.util.Objects.deepEquals(this.fixCommonMistakes, other.fixCommonMistakes) &&
            java.util.Objects.deepEquals(this.id, other.id) &&
            java.util.Objects.deepEquals(this.termId, other.termId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            capitalize,
            fixCase,
            fixCommonMistakes,
            id,
            termId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ApprovedTermExtension.class,
                "capitalize", capitalize,
                "fixCase", fixCase,
                "fixCommonMistakes", fixCommonMistakes,
                "id", id,
                "termId", termId);
    }
    
    public final static class Builder {
 
        private Boolean capitalize;
 
        private Boolean fixCase;
 
        private Boolean fixCommonMistakes;
 
        private Optional<? extends Long> id = Optional.empty();
 
        private Long termId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder capitalize(boolean capitalize) {
            Utils.checkNotNull(capitalize, "capitalize");
            this.capitalize = capitalize;
            return this;
        }

        public Builder fixCase(boolean fixCase) {
            Utils.checkNotNull(fixCase, "fixCase");
            this.fixCase = fixCase;
            return this;
        }

        public Builder fixCommonMistakes(boolean fixCommonMistakes) {
            Utils.checkNotNull(fixCommonMistakes, "fixCommonMistakes");
            this.fixCommonMistakes = fixCommonMistakes;
            return this;
        }

        public Builder id(long id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        public Builder id(Optional<? extends Long> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder termId(long termId) {
            Utils.checkNotNull(termId, "termId");
            this.termId = termId;
            return this;
        }
        
        public ApprovedTermExtension build() {
            return new ApprovedTermExtension(
                capitalize,
                fixCase,
                fixCommonMistakes,
                id,
                termId);
        }
    }
}

