/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class CompletionResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("choices")
    private Optional<? extends java.util.List<CompletionGenerationChoice>> choices;

    @JsonCreator
    public CompletionResponse(
            @JsonProperty("choices") Optional<? extends java.util.List<CompletionGenerationChoice>> choices) {
        Utils.checkNotNull(choices, "choices");
        this.choices = choices;
    }
    
    public CompletionResponse() {
        this(Optional.empty());
    }

    @JsonIgnore
    public Optional<? extends java.util.List<CompletionGenerationChoice>> choices() {
        return choices;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CompletionResponse withChoices(java.util.List<CompletionGenerationChoice> choices) {
        Utils.checkNotNull(choices, "choices");
        this.choices = Optional.ofNullable(choices);
        return this;
    }

    public CompletionResponse withChoices(Optional<? extends java.util.List<CompletionGenerationChoice>> choices) {
        Utils.checkNotNull(choices, "choices");
        this.choices = choices;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompletionResponse other = (CompletionResponse) o;
        return 
            java.util.Objects.deepEquals(this.choices, other.choices);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            choices);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompletionResponse.class,
                "choices", choices);
    }
    
    public final static class Builder {
 
        private Optional<? extends java.util.List<CompletionGenerationChoice>> choices = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder choices(java.util.List<CompletionGenerationChoice> choices) {
            Utils.checkNotNull(choices, "choices");
            this.choices = Optional.ofNullable(choices);
            return this;
        }

        public Builder choices(Optional<? extends java.util.List<CompletionGenerationChoice>> choices) {
            Utils.checkNotNull(choices, "choices");
            this.choices = choices;
            return this;
        }
        
        public CompletionResponse build() {
            return new CompletionResponse(
                choices);
        }
    }
}

