/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class CorrectionResponse {

    @JsonProperty("correct")
    private String correct;

    @JsonCreator
    public CorrectionResponse(
            @JsonProperty("correct") String correct) {
        Utils.checkNotNull(correct, "correct");
        this.correct = correct;
    }

    @JsonIgnore
    public String correct() {
        return correct;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CorrectionResponse withCorrect(String correct) {
        Utils.checkNotNull(correct, "correct");
        this.correct = correct;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CorrectionResponse other = (CorrectionResponse) o;
        return 
            java.util.Objects.deepEquals(this.correct, other.correct);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            correct);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CorrectionResponse.class,
                "correct", correct);
    }
    
    public final static class Builder {
 
        private String correct;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder correct(String correct) {
            Utils.checkNotNull(correct, "correct");
            this.correct = correct;
            return this;
        }
        
        public CorrectionResponse build() {
            return new CorrectionResponse(
                correct);
        }
    }
}

