/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class CreateCustomizationRequest {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("additionalHyperParameters")
    private Optional<? extends HyperParameters> additionalHyperParameters;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("batchSize")
    private Optional<? extends Long> batchSize;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private Optional<? extends String> description;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("epochs")
    private Optional<? extends Long> epochs;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("learningRate")
    private Optional<? extends Double> learningRate;

    @JsonProperty("name")
    private String name;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("promptTemplate")
    private Optional<? extends String> promptTemplate;

    @JsonProperty("trainingDatasetFileId")
    private String trainingDatasetFileId;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validationDatasetFileId")
    private Optional<? extends String> validationDatasetFileId;

    @JsonCreator
    public CreateCustomizationRequest(
            @JsonProperty("additionalHyperParameters") Optional<? extends HyperParameters> additionalHyperParameters,
            @JsonProperty("batchSize") Optional<? extends Long> batchSize,
            @JsonProperty("description") Optional<? extends String> description,
            @JsonProperty("epochs") Optional<? extends Long> epochs,
            @JsonProperty("learningRate") Optional<? extends Double> learningRate,
            @JsonProperty("name") String name,
            @JsonProperty("promptTemplate") Optional<? extends String> promptTemplate,
            @JsonProperty("trainingDatasetFileId") String trainingDatasetFileId,
            @JsonProperty("validationDatasetFileId") Optional<? extends String> validationDatasetFileId) {
        Utils.checkNotNull(additionalHyperParameters, "additionalHyperParameters");
        Utils.checkNotNull(batchSize, "batchSize");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(epochs, "epochs");
        Utils.checkNotNull(learningRate, "learningRate");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(promptTemplate, "promptTemplate");
        Utils.checkNotNull(trainingDatasetFileId, "trainingDatasetFileId");
        Utils.checkNotNull(validationDatasetFileId, "validationDatasetFileId");
        this.additionalHyperParameters = additionalHyperParameters;
        this.batchSize = batchSize;
        this.description = description;
        this.epochs = epochs;
        this.learningRate = learningRate;
        this.name = name;
        this.promptTemplate = promptTemplate;
        this.trainingDatasetFileId = trainingDatasetFileId;
        this.validationDatasetFileId = validationDatasetFileId;
    }
    
    public CreateCustomizationRequest(
            String name,
            String trainingDatasetFileId) {
        this(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), name, Optional.empty(), trainingDatasetFileId, Optional.empty());
    }

    @JsonIgnore
    public Optional<? extends HyperParameters> additionalHyperParameters() {
        return additionalHyperParameters;
    }

    @JsonIgnore
    public Optional<? extends Long> batchSize() {
        return batchSize;
    }

    @JsonIgnore
    public Optional<? extends String> description() {
        return description;
    }

    @JsonIgnore
    public Optional<? extends Long> epochs() {
        return epochs;
    }

    @JsonIgnore
    public Optional<? extends Double> learningRate() {
        return learningRate;
    }

    @JsonIgnore
    public String name() {
        return name;
    }

    @JsonIgnore
    public Optional<? extends String> promptTemplate() {
        return promptTemplate;
    }

    @JsonIgnore
    public String trainingDatasetFileId() {
        return trainingDatasetFileId;
    }

    @JsonIgnore
    public Optional<? extends String> validationDatasetFileId() {
        return validationDatasetFileId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreateCustomizationRequest withAdditionalHyperParameters(HyperParameters additionalHyperParameters) {
        Utils.checkNotNull(additionalHyperParameters, "additionalHyperParameters");
        this.additionalHyperParameters = Optional.ofNullable(additionalHyperParameters);
        return this;
    }

    public CreateCustomizationRequest withAdditionalHyperParameters(Optional<? extends HyperParameters> additionalHyperParameters) {
        Utils.checkNotNull(additionalHyperParameters, "additionalHyperParameters");
        this.additionalHyperParameters = additionalHyperParameters;
        return this;
    }

    public CreateCustomizationRequest withBatchSize(long batchSize) {
        Utils.checkNotNull(batchSize, "batchSize");
        this.batchSize = Optional.ofNullable(batchSize);
        return this;
    }

    public CreateCustomizationRequest withBatchSize(Optional<? extends Long> batchSize) {
        Utils.checkNotNull(batchSize, "batchSize");
        this.batchSize = batchSize;
        return this;
    }

    public CreateCustomizationRequest withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = Optional.ofNullable(description);
        return this;
    }

    public CreateCustomizationRequest withDescription(Optional<? extends String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    public CreateCustomizationRequest withEpochs(long epochs) {
        Utils.checkNotNull(epochs, "epochs");
        this.epochs = Optional.ofNullable(epochs);
        return this;
    }

    public CreateCustomizationRequest withEpochs(Optional<? extends Long> epochs) {
        Utils.checkNotNull(epochs, "epochs");
        this.epochs = epochs;
        return this;
    }

    public CreateCustomizationRequest withLearningRate(double learningRate) {
        Utils.checkNotNull(learningRate, "learningRate");
        this.learningRate = Optional.ofNullable(learningRate);
        return this;
    }

    public CreateCustomizationRequest withLearningRate(Optional<? extends Double> learningRate) {
        Utils.checkNotNull(learningRate, "learningRate");
        this.learningRate = learningRate;
        return this;
    }

    public CreateCustomizationRequest withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public CreateCustomizationRequest withPromptTemplate(String promptTemplate) {
        Utils.checkNotNull(promptTemplate, "promptTemplate");
        this.promptTemplate = Optional.ofNullable(promptTemplate);
        return this;
    }

    public CreateCustomizationRequest withPromptTemplate(Optional<? extends String> promptTemplate) {
        Utils.checkNotNull(promptTemplate, "promptTemplate");
        this.promptTemplate = promptTemplate;
        return this;
    }

    public CreateCustomizationRequest withTrainingDatasetFileId(String trainingDatasetFileId) {
        Utils.checkNotNull(trainingDatasetFileId, "trainingDatasetFileId");
        this.trainingDatasetFileId = trainingDatasetFileId;
        return this;
    }

    public CreateCustomizationRequest withValidationDatasetFileId(String validationDatasetFileId) {
        Utils.checkNotNull(validationDatasetFileId, "validationDatasetFileId");
        this.validationDatasetFileId = Optional.ofNullable(validationDatasetFileId);
        return this;
    }

    public CreateCustomizationRequest withValidationDatasetFileId(Optional<? extends String> validationDatasetFileId) {
        Utils.checkNotNull(validationDatasetFileId, "validationDatasetFileId");
        this.validationDatasetFileId = validationDatasetFileId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCustomizationRequest other = (CreateCustomizationRequest) o;
        return 
            java.util.Objects.deepEquals(this.additionalHyperParameters, other.additionalHyperParameters) &&
            java.util.Objects.deepEquals(this.batchSize, other.batchSize) &&
            java.util.Objects.deepEquals(this.description, other.description) &&
            java.util.Objects.deepEquals(this.epochs, other.epochs) &&
            java.util.Objects.deepEquals(this.learningRate, other.learningRate) &&
            java.util.Objects.deepEquals(this.name, other.name) &&
            java.util.Objects.deepEquals(this.promptTemplate, other.promptTemplate) &&
            java.util.Objects.deepEquals(this.trainingDatasetFileId, other.trainingDatasetFileId) &&
            java.util.Objects.deepEquals(this.validationDatasetFileId, other.validationDatasetFileId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            additionalHyperParameters,
            batchSize,
            description,
            epochs,
            learningRate,
            name,
            promptTemplate,
            trainingDatasetFileId,
            validationDatasetFileId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCustomizationRequest.class,
                "additionalHyperParameters", additionalHyperParameters,
                "batchSize", batchSize,
                "description", description,
                "epochs", epochs,
                "learningRate", learningRate,
                "name", name,
                "promptTemplate", promptTemplate,
                "trainingDatasetFileId", trainingDatasetFileId,
                "validationDatasetFileId", validationDatasetFileId);
    }
    
    public final static class Builder {
 
        private Optional<? extends HyperParameters> additionalHyperParameters = Optional.empty();
 
        private Optional<? extends Long> batchSize = Optional.empty();
 
        private Optional<? extends String> description = Optional.empty();
 
        private Optional<? extends Long> epochs = Optional.empty();
 
        private Optional<? extends Double> learningRate = Optional.empty();
 
        private String name;
 
        private Optional<? extends String> promptTemplate = Optional.empty();
 
        private String trainingDatasetFileId;
 
        private Optional<? extends String> validationDatasetFileId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder additionalHyperParameters(HyperParameters additionalHyperParameters) {
            Utils.checkNotNull(additionalHyperParameters, "additionalHyperParameters");
            this.additionalHyperParameters = Optional.ofNullable(additionalHyperParameters);
            return this;
        }

        public Builder additionalHyperParameters(Optional<? extends HyperParameters> additionalHyperParameters) {
            Utils.checkNotNull(additionalHyperParameters, "additionalHyperParameters");
            this.additionalHyperParameters = additionalHyperParameters;
            return this;
        }

        public Builder batchSize(long batchSize) {
            Utils.checkNotNull(batchSize, "batchSize");
            this.batchSize = Optional.ofNullable(batchSize);
            return this;
        }

        public Builder batchSize(Optional<? extends Long> batchSize) {
            Utils.checkNotNull(batchSize, "batchSize");
            this.batchSize = batchSize;
            return this;
        }

        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = Optional.ofNullable(description);
            return this;
        }

        public Builder description(Optional<? extends String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }

        public Builder epochs(long epochs) {
            Utils.checkNotNull(epochs, "epochs");
            this.epochs = Optional.ofNullable(epochs);
            return this;
        }

        public Builder epochs(Optional<? extends Long> epochs) {
            Utils.checkNotNull(epochs, "epochs");
            this.epochs = epochs;
            return this;
        }

        public Builder learningRate(double learningRate) {
            Utils.checkNotNull(learningRate, "learningRate");
            this.learningRate = Optional.ofNullable(learningRate);
            return this;
        }

        public Builder learningRate(Optional<? extends Double> learningRate) {
            Utils.checkNotNull(learningRate, "learningRate");
            this.learningRate = learningRate;
            return this;
        }

        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }

        public Builder promptTemplate(String promptTemplate) {
            Utils.checkNotNull(promptTemplate, "promptTemplate");
            this.promptTemplate = Optional.ofNullable(promptTemplate);
            return this;
        }

        public Builder promptTemplate(Optional<? extends String> promptTemplate) {
            Utils.checkNotNull(promptTemplate, "promptTemplate");
            this.promptTemplate = promptTemplate;
            return this;
        }

        public Builder trainingDatasetFileId(String trainingDatasetFileId) {
            Utils.checkNotNull(trainingDatasetFileId, "trainingDatasetFileId");
            this.trainingDatasetFileId = trainingDatasetFileId;
            return this;
        }

        public Builder validationDatasetFileId(String validationDatasetFileId) {
            Utils.checkNotNull(validationDatasetFileId, "validationDatasetFileId");
            this.validationDatasetFileId = Optional.ofNullable(validationDatasetFileId);
            return this;
        }

        public Builder validationDatasetFileId(Optional<? extends String> validationDatasetFileId) {
            Utils.checkNotNull(validationDatasetFileId, "validationDatasetFileId");
            this.validationDatasetFileId = validationDatasetFileId;
            return this;
        }
        
        public CreateCustomizationRequest build() {
            return new CreateCustomizationRequest(
                additionalHyperParameters,
                batchSize,
                description,
                epochs,
                learningRate,
                name,
                promptTemplate,
                trainingDatasetFileId,
                validationDatasetFileId);
        }
    }
}

