/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk;

import com.writer.sdk.utils.Hook.SdkInitData;
import com.writer.sdk.utils.HTTPClient;
import com.writer.sdk.utils.RetryConfig;
import com.writer.sdk.models.shared.Security;
import java.util.Map;
import java.util.HashMap;
import java.util.Optional;

class SDKConfiguration {
    public SecuritySource securitySource;
    
    public Optional<SecuritySource> securitySource() {
        return Optional.ofNullable(securitySource);
    }
    public HTTPClient defaultClient;
      public String serverUrl;
    public int serverIdx = 0;
    public String language = "java";
    public String openapiDocVersion = "1.7";
    public String sdkVersion = "0.45.0";
    public String genVersion = "2.312.1";
    public String userAgent = "speakeasy-sdk/java 0.45.0 2.312.1 1.7 com.writer.sdk";

    private com.writer.sdk.utils.Hooks _hooks = new com.writer.sdk.utils.Hooks();

    public com.writer.sdk.utils.Hooks hooks() {
        return _hooks;
    }

    public void setHooks(com.writer.sdk.utils.Hooks hooks) {
        this._hooks = hooks;
    }

    /** 
     * Initializes state (for example hooks).
     **/
    public void initialize() {

    }

    public Map<String, Map<String, Map<String, java.lang.Object>>> globals = new HashMap<>(){{
        put("parameters", new HashMap<>());
    }};
    
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
