/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.SpeakeasyMetadata;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class AddTermsRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    private Optional<? extends Long> organizationId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    private long teamId;

    @JsonCreator
    public AddTermsRequest(
            com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest,
            Optional<? extends Long> organizationId,
            long teamId) {
        Utils.checkNotNull(createTermsRequest, "createTermsRequest");
        Utils.checkNotNull(organizationId, "organizationId");
        Utils.checkNotNull(teamId, "teamId");
        this.createTermsRequest = createTermsRequest;
        this.organizationId = organizationId;
        this.teamId = teamId;
    }
    
    public AddTermsRequest(
            com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest,
            long teamId) {
        this(createTermsRequest, Optional.empty(), teamId);
    }

    @JsonIgnore
    public com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest() {
        return createTermsRequest;
    }

    @JsonIgnore
    public Optional<? extends Long> organizationId() {
        return organizationId;
    }

    @JsonIgnore
    public long teamId() {
        return teamId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public AddTermsRequest withCreateTermsRequest(com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest) {
        Utils.checkNotNull(createTermsRequest, "createTermsRequest");
        this.createTermsRequest = createTermsRequest;
        return this;
    }

    public AddTermsRequest withOrganizationId(long organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = Optional.ofNullable(organizationId);
        return this;
    }

    public AddTermsRequest withOrganizationId(Optional<? extends Long> organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = organizationId;
        return this;
    }

    public AddTermsRequest withTeamId(long teamId) {
        Utils.checkNotNull(teamId, "teamId");
        this.teamId = teamId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AddTermsRequest other = (AddTermsRequest) o;
        return 
            java.util.Objects.deepEquals(this.createTermsRequest, other.createTermsRequest) &&
            java.util.Objects.deepEquals(this.organizationId, other.organizationId) &&
            java.util.Objects.deepEquals(this.teamId, other.teamId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            createTermsRequest,
            organizationId,
            teamId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AddTermsRequest.class,
                "createTermsRequest", createTermsRequest,
                "organizationId", organizationId,
                "teamId", teamId);
    }
    
    public final static class Builder {
 
        private com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest;
 
        private Optional<? extends Long> organizationId = Optional.empty();
 
        private Long teamId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder createTermsRequest(com.writer.sdk.models.shared.CreateTermsRequest createTermsRequest) {
            Utils.checkNotNull(createTermsRequest, "createTermsRequest");
            this.createTermsRequest = createTermsRequest;
            return this;
        }

        public Builder organizationId(long organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        public Builder organizationId(Optional<? extends Long> organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = organizationId;
            return this;
        }

        public Builder teamId(long teamId) {
            Utils.checkNotNull(teamId, "teamId");
            this.teamId = teamId;
            return this;
        }
        
        public AddTermsRequest build() {
            return new AddTermsRequest(
                createTermsRequest,
                organizationId,
                teamId);
        }
    }
}

