/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.SpeakeasyMetadata;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class CreateCompletionRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private com.writer.sdk.models.shared.CompletionRequest completionRequest;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=modelId")
    private String modelId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    private Optional<? extends Long> organizationId;

    @JsonCreator
    public CreateCompletionRequest(
            com.writer.sdk.models.shared.CompletionRequest completionRequest,
            String modelId,
            Optional<? extends Long> organizationId) {
        Utils.checkNotNull(completionRequest, "completionRequest");
        Utils.checkNotNull(modelId, "modelId");
        Utils.checkNotNull(organizationId, "organizationId");
        this.completionRequest = completionRequest;
        this.modelId = modelId;
        this.organizationId = organizationId;
    }
    
    public CreateCompletionRequest(
            com.writer.sdk.models.shared.CompletionRequest completionRequest,
            String modelId) {
        this(completionRequest, modelId, Optional.empty());
    }

    @JsonIgnore
    public com.writer.sdk.models.shared.CompletionRequest completionRequest() {
        return completionRequest;
    }

    @JsonIgnore
    public String modelId() {
        return modelId;
    }

    @JsonIgnore
    public Optional<? extends Long> organizationId() {
        return organizationId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreateCompletionRequest withCompletionRequest(com.writer.sdk.models.shared.CompletionRequest completionRequest) {
        Utils.checkNotNull(completionRequest, "completionRequest");
        this.completionRequest = completionRequest;
        return this;
    }

    public CreateCompletionRequest withModelId(String modelId) {
        Utils.checkNotNull(modelId, "modelId");
        this.modelId = modelId;
        return this;
    }

    public CreateCompletionRequest withOrganizationId(long organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = Optional.ofNullable(organizationId);
        return this;
    }

    public CreateCompletionRequest withOrganizationId(Optional<? extends Long> organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = organizationId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCompletionRequest other = (CreateCompletionRequest) o;
        return 
            java.util.Objects.deepEquals(this.completionRequest, other.completionRequest) &&
            java.util.Objects.deepEquals(this.modelId, other.modelId) &&
            java.util.Objects.deepEquals(this.organizationId, other.organizationId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            completionRequest,
            modelId,
            organizationId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCompletionRequest.class,
                "completionRequest", completionRequest,
                "modelId", modelId,
                "organizationId", organizationId);
    }
    
    public final static class Builder {
 
        private com.writer.sdk.models.shared.CompletionRequest completionRequest;
 
        private String modelId;
 
        private Optional<? extends Long> organizationId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder completionRequest(com.writer.sdk.models.shared.CompletionRequest completionRequest) {
            Utils.checkNotNull(completionRequest, "completionRequest");
            this.completionRequest = completionRequest;
            return this;
        }

        public Builder modelId(String modelId) {
            Utils.checkNotNull(modelId, "modelId");
            this.modelId = modelId;
            return this;
        }

        public Builder organizationId(long organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        public Builder organizationId(Optional<? extends Long> organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = organizationId;
            return this;
        }
        
        public CreateCompletionRequest build() {
            return new CreateCompletionRequest(
                completionRequest,
                modelId,
                organizationId);
        }
    }
}

