/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.SpeakeasyMetadata;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class DeleteFileRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=fileId")
    private String fileId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    private Optional<? extends Long> organizationId;

    @JsonCreator
    public DeleteFileRequest(
            String fileId,
            Optional<? extends Long> organizationId) {
        Utils.checkNotNull(fileId, "fileId");
        Utils.checkNotNull(organizationId, "organizationId");
        this.fileId = fileId;
        this.organizationId = organizationId;
    }
    
    public DeleteFileRequest(
            String fileId) {
        this(fileId, Optional.empty());
    }

    @JsonIgnore
    public String fileId() {
        return fileId;
    }

    @JsonIgnore
    public Optional<? extends Long> organizationId() {
        return organizationId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public DeleteFileRequest withFileId(String fileId) {
        Utils.checkNotNull(fileId, "fileId");
        this.fileId = fileId;
        return this;
    }

    public DeleteFileRequest withOrganizationId(long organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = Optional.ofNullable(organizationId);
        return this;
    }

    public DeleteFileRequest withOrganizationId(Optional<? extends Long> organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = organizationId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteFileRequest other = (DeleteFileRequest) o;
        return 
            java.util.Objects.deepEquals(this.fileId, other.fileId) &&
            java.util.Objects.deepEquals(this.organizationId, other.organizationId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            fileId,
            organizationId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteFileRequest.class,
                "fileId", fileId,
                "organizationId", organizationId);
    }
    
    public final static class Builder {
 
        private String fileId;
 
        private Optional<? extends Long> organizationId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder fileId(String fileId) {
            Utils.checkNotNull(fileId, "fileId");
            this.fileId = fileId;
            return this;
        }

        public Builder organizationId(long organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        public Builder organizationId(Optional<? extends Long> organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = organizationId;
            return this;
        }
        
        public DeleteFileRequest build() {
            return new DeleteFileRequest(
                fileId,
                organizationId);
        }
    }
}

