/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.SpeakeasyMetadata;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class FetchCustomizedModelFileRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customizationId")
    private String customizationId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=modelId")
    private String modelId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    private Optional<? extends Long> organizationId;

    @JsonCreator
    public FetchCustomizedModelFileRequest(
            String customizationId,
            String modelId,
            Optional<? extends Long> organizationId) {
        Utils.checkNotNull(customizationId, "customizationId");
        Utils.checkNotNull(modelId, "modelId");
        Utils.checkNotNull(organizationId, "organizationId");
        this.customizationId = customizationId;
        this.modelId = modelId;
        this.organizationId = organizationId;
    }
    
    public FetchCustomizedModelFileRequest(
            String customizationId,
            String modelId) {
        this(customizationId, modelId, Optional.empty());
    }

    @JsonIgnore
    public String customizationId() {
        return customizationId;
    }

    @JsonIgnore
    public String modelId() {
        return modelId;
    }

    @JsonIgnore
    public Optional<? extends Long> organizationId() {
        return organizationId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public FetchCustomizedModelFileRequest withCustomizationId(String customizationId) {
        Utils.checkNotNull(customizationId, "customizationId");
        this.customizationId = customizationId;
        return this;
    }

    public FetchCustomizedModelFileRequest withModelId(String modelId) {
        Utils.checkNotNull(modelId, "modelId");
        this.modelId = modelId;
        return this;
    }

    public FetchCustomizedModelFileRequest withOrganizationId(long organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = Optional.ofNullable(organizationId);
        return this;
    }

    public FetchCustomizedModelFileRequest withOrganizationId(Optional<? extends Long> organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = organizationId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FetchCustomizedModelFileRequest other = (FetchCustomizedModelFileRequest) o;
        return 
            java.util.Objects.deepEquals(this.customizationId, other.customizationId) &&
            java.util.Objects.deepEquals(this.modelId, other.modelId) &&
            java.util.Objects.deepEquals(this.organizationId, other.organizationId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            customizationId,
            modelId,
            organizationId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(FetchCustomizedModelFileRequest.class,
                "customizationId", customizationId,
                "modelId", modelId,
                "organizationId", organizationId);
    }
    
    public final static class Builder {
 
        private String customizationId;
 
        private String modelId;
 
        private Optional<? extends Long> organizationId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder customizationId(String customizationId) {
            Utils.checkNotNull(customizationId, "customizationId");
            this.customizationId = customizationId;
            return this;
        }

        public Builder modelId(String modelId) {
            Utils.checkNotNull(modelId, "modelId");
            this.modelId = modelId;
            return this;
        }

        public Builder organizationId(long organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        public Builder organizationId(Optional<? extends Long> organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = organizationId;
            return this;
        }
        
        public FetchCustomizedModelFileRequest build() {
            return new FetchCustomizedModelFileRequest(
                customizationId,
                modelId,
                organizationId);
        }
    }
}

