/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.utils.SpeakeasyMetadata;
import com.writer.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class ListTemplatesRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    private Optional<? extends Long> organizationId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    private long teamId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=templateId")
    private String templateId;

    @JsonCreator
    public ListTemplatesRequest(
            Optional<? extends Long> organizationId,
            long teamId,
            String templateId) {
        Utils.checkNotNull(organizationId, "organizationId");
        Utils.checkNotNull(teamId, "teamId");
        Utils.checkNotNull(templateId, "templateId");
        this.organizationId = organizationId;
        this.teamId = teamId;
        this.templateId = templateId;
    }
    
    public ListTemplatesRequest(
            long teamId,
            String templateId) {
        this(Optional.empty(), teamId, templateId);
    }

    @JsonIgnore
    public Optional<? extends Long> organizationId() {
        return organizationId;
    }

    @JsonIgnore
    public long teamId() {
        return teamId;
    }

    @JsonIgnore
    public String templateId() {
        return templateId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ListTemplatesRequest withOrganizationId(long organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = Optional.ofNullable(organizationId);
        return this;
    }

    public ListTemplatesRequest withOrganizationId(Optional<? extends Long> organizationId) {
        Utils.checkNotNull(organizationId, "organizationId");
        this.organizationId = organizationId;
        return this;
    }

    public ListTemplatesRequest withTeamId(long teamId) {
        Utils.checkNotNull(teamId, "teamId");
        this.teamId = teamId;
        return this;
    }

    public ListTemplatesRequest withTemplateId(String templateId) {
        Utils.checkNotNull(templateId, "templateId");
        this.templateId = templateId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListTemplatesRequest other = (ListTemplatesRequest) o;
        return 
            java.util.Objects.deepEquals(this.organizationId, other.organizationId) &&
            java.util.Objects.deepEquals(this.teamId, other.teamId) &&
            java.util.Objects.deepEquals(this.templateId, other.templateId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            organizationId,
            teamId,
            templateId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListTemplatesRequest.class,
                "organizationId", organizationId,
                "teamId", teamId,
                "templateId", templateId);
    }
    
    public final static class Builder {
 
        private Optional<? extends Long> organizationId = Optional.empty();
 
        private Long teamId;
 
        private String templateId;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder organizationId(long organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = Optional.ofNullable(organizationId);
            return this;
        }

        public Builder organizationId(Optional<? extends Long> organizationId) {
            Utils.checkNotNull(organizationId, "organizationId");
            this.organizationId = organizationId;
            return this;
        }

        public Builder teamId(long teamId) {
            Utils.checkNotNull(teamId, "teamId");
            this.teamId = teamId;
            return this;
        }

        public Builder templateId(String templateId) {
            Utils.checkNotNull(templateId, "templateId");
            this.templateId = templateId;
            return this;
        }
        
        public ListTemplatesRequest build() {
            return new ListTemplatesRequest(
                organizationId,
                teamId,
                templateId);
        }
    }
}

