/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.writer.sdk.models.errors.SDKError;
import com.writer.sdk.utils.LazySingletonValue;
import com.writer.sdk.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class ListTemplatesRequestBuilder {

    private ListTemplatesRequest request;
    private final SDKMethodInterfaces.MethodCallListTemplates sdk;

    public ListTemplatesRequestBuilder(SDKMethodInterfaces.MethodCallListTemplates sdk) {
        this.sdk = sdk;
    }

    public ListTemplatesRequestBuilder request(ListTemplatesRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListTemplatesResponse call() throws Exception {

        return sdk.listTemplates(
            request);
    }
}
